### ISSUE TITLE
Version on pub.dev is 2.2.1 instead of 2.3.0

### ISSUE THREAD

**Issue by gourgouris** [pikaju/flutter-maps-launcher#40]
As a result, the fix of (https://github.com/pikaju/flutter-maps-launcher/pull/32) is not published, so the plugin is still not compatible with AGP 8.0

Relevant comment: (https://github.com/pikaju/flutter-maps-launcher/pull/32#issuecomment-1985597947)

**Comment by mvarendorff2** [comment]
Yup; while the changelog mentions compatibility with AGP 8.x for 2.2.1, downloading the [source bundle](https://pub.dev/packages/maps_launcher/versions/2.2.1.tar.gz) from the version tab on pub shows that the relevant section is missing in android/build.gradle.

Workaround for now is referencing the package from git:
```yml
maps_launcher:
  git:
    url: https://github.com/pikaju/flutter-maps-launcher.git
    ref: master
```
